### ISSUE TITLE
WeatherParser Files Update - JDWS-02

### ISSUE THREAD

**Issue by MyCodeIsntWorking** [adriaanjelle/Sienna-2.0#2]
Hi adriaanjelle,

can you update the WeatherParser Files on JDWS-02 Weather Skin also, this is broken since a week or so.

Sry to write the issue here, but on the JDWS-02 give no issue option.

Thank you and best regards

**Comment by adriaanjelle** [comment]
An update's coming soon :)

**Comment by MyCodeIsntWorking** [comment]
Thank you for the update.
Great work!
