### ISSUE TITLE
Sienna not pulling weather info as of ~6/15/2024

### ISSUE THREAD

**Issue by mogno-jelly** [adriaanjelle/Sienna-2.0#6]
Hello, I'm seeing an issue that looks pretty much like what was brought up in https://github.com/adriaanjelle/Sienna-2.0/issues/3 previously.  The error showing in logs: _Invalid TimeStampFormat: %Y-%m-%dT%H:%M:%S_

Here's what I'm seeing:
![image](https://github.com/adriaanjelle/Sienna-2.0/assets/84936629/a474b4e1-cf2c-4afb-b3d8-017c61d12bb6)

![image](https://github.com/adriaanjelle/Sienna-2.0/assets/84936629/3cd65bb3-c08f-41a9-a496-c84147b1f0a0)

Thank you in advance!

**Comment by adriaanjelle** [comment]
Try the latest version, this should be fixed now :)

**Comment by mogno-jelly** [comment]
> Try the latest version, this should be fixed now :)

Yup all good now - thank you!
